import Link from "next/link";
import { ArrowLeft, Boxes, Building2, CircleDollarSign, ExternalLink, Package, Utensils } from "lucide-react";
import { getKitchenCatalogItemDetail, getKitchenCatalogStatusMeta } from "@/lib/kitchen/inventory/catalog";
import { listKitchenInventoryCategories, listKitchenInventoryUnits } from "@/lib/kitchen/inventory/queries";
import { StatePanel } from "@/components/ui/state-panel";
import { KitchenPageHeader } from "../../_components/kitchen-page-header";
import { resolveKitchenPage } from "../../_lib/page-access";
import { getCurrentTenantModulePageAccessMap, hasModulePageAccess } from "@/lib/auth/module-page-access";
import { CatalogItemDialog } from "../_components/catalog-item-dialog";

type Props = { params: Promise<{ tenantSlug: string; itemId: string }> };
const money = (value: number | null) => value == null ? "—" : `$${value.toLocaleString("es-MX", { minimumFractionDigits: 2, maximumFractionDigits: 4 })}`;
export default async function KitchenCatalogItemPage({ params }: Props) {
  const { tenantSlug, itemId } = await params; const access = await resolveKitchenPage(tenantSlug, "kitchen_inventory", "items");
  if (!access.ok) return <StatePanel kind="permission" title="Sin permisos" message="No tienes acceso al detalle del insumo." />;
  const [detail, categories, units, accessMap] = await Promise.all([getKitchenCatalogItemDetail(access.tenant.tenantId, itemId), listKitchenInventoryCategories(access.tenant.tenantId), listKitchenInventoryUnits(access.tenant.tenantId), getCurrentTenantModulePageAccessMap(access.tenant.tenantId, "kitchen_inventory")]);
  if (!detail) return <StatePanel kind="empty" title="Insumo no encontrado" message="El insumo no existe o no pertenece a este tenant." />;
  const canManage = hasModulePageAccess(accessMap.items ?? "none", "manage"); const status = getKitchenCatalogStatusMeta(detail.status);
  return <div className="space-y-4">
    <Link href={`/${tenantSlug}/kitchen/catalog`} className="inline-flex items-center gap-1 text-sm text-muted hover:text-foreground"><ArrowLeft className="h-4 w-4" />Volver al catálogo</Link>
    <KitchenPageHeader eyebrow="Catálogo de insumos" title={detail.item.name} description={status.description} actions={canManage ? <CatalogItemDialog tenantSlug={tenantSlug} categories={categories} units={units} item={detail.item} canChangeUnit={detail.canChangeUnit} /> : null} />
    <div className="grid gap-3 md:grid-cols-4"><div className="rounded border border-border bg-surface p-4"><div className="flex items-center gap-2 text-xs text-muted"><Package className="h-4 w-4" aria-hidden="true" />Estado</div><div className="mt-2 font-medium">{status.label}</div></div><div className="rounded border border-border bg-surface p-4"><div className="flex items-center gap-2 text-xs text-muted"><CircleDollarSign className="h-4 w-4" aria-hidden="true" />Costo unitario</div><div className="mt-2 font-medium">{money(Number(detail.item.current_unit_cost))} / {detail.unitCode ?? "ud"}</div></div><div className="rounded border border-border bg-surface p-4"><div className="flex items-center gap-2 text-xs text-muted"><Building2 className="h-4 w-4" aria-hidden="true" />Proveedor referencia</div><div className="mt-2 font-medium">{detail.referenceSupplierName ?? "—"}</div></div><div className="rounded border border-border bg-surface p-4"><div className="flex items-center gap-2 text-xs text-muted"><Utensils className="h-4 w-4" aria-hidden="true" />Uso en recetas</div><div className="mt-2 font-medium">{detail.recipeLineCount}</div></div></div>
    <section className="rounded border border-border bg-surface p-4"><h2 className="font-semibold">Datos básicos</h2><dl className="mt-3 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-muted">Categoría</dt><dd>{detail.categoryName ?? "Sin categoría"}</dd></div><div><dt className="text-muted">Unidad operativa</dt><dd>{detail.unitCode ?? "—"}</dd></div><div><dt className="text-muted">Descripción</dt><dd>{detail.item.description ?? "—"}</dd></div></dl></section>
    <section className="rounded border border-border bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="flex items-center gap-2"><Boxes className="h-4 w-4 text-primary" aria-hidden="true" /><h2 className="font-semibold">Presentaciones y precios</h2></div><p className="mt-1 text-sm text-muted">Consulta rápida de la presentación de referencia. La administración avanzada permanece disponible.</p></div><Link href={`/${tenantSlug}/kitchen/inventory/presentaciones-precios`} className="inline-flex items-center gap-1 text-sm text-primary hover:underline">Administrar en vista avanzada <ExternalLink className="h-4 w-4" /></Link></div><div className="mt-4 divide-y divide-border">{detail.presentations.length ? detail.presentations.map((presentation) => <div key={presentation.id} className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0"><div><div className="font-medium">{presentation.purchaseUnitCode ?? "—"} · {presentation.quantityPerPurchaseUnit} {presentation.inventoryUnitCode ?? detail.unitCode ?? ""}{presentation.isReference ? <span className="ml-2 rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">Referencia</span> : null}</div><div className="text-xs text-muted">{presentation.supplierName ?? "Sin proveedor"} · {presentation.isActive ? "Activa" : "Retirada"}</div></div><div className="text-right text-sm"><div>{presentation.pricePerPurchaseUnit == null ? "Precio pendiente" : `${money(presentation.pricePerPurchaseUnit)} por presentación`}</div><div className="text-xs text-muted">Costo derivado: {money(presentation.derivedUnitCost)} / {detail.unitCode ?? "ud"}</div></div></div>) : <p className="py-3 text-sm text-muted">Aún no hay presentaciones configuradas.</p>}</div></section>
    <section className="rounded border border-border bg-surface p-4"><h2 className="font-semibold">Uso e historial</h2><p className="mt-2 text-sm text-muted">Este insumo aparece en {detail.recipeLineCount} líneas de receta y tiene {detail.historicalUsageCount} referencias operativas o históricas. Por seguridad, la unidad solo puede cambiarse cuando no existen referencias.</p></section>
  </div>;
}
